import { DocumentTemplateDto } from './dto/document-template.dto';

export const BUILT_IN_TEMPLATES: readonly DocumentTemplateDto[] = [
  {
    id: 'builtin:guide',
    name: 'How-to guide',
    description: 'A task-focused guide with prerequisites and verification.',
    suggestedPath: 'guides/how-to.md',
    contentRaw: [
      '---',
      'title: How-to guide',
      'tags: [guide]',
      'status: draft',
      '---',
      '',
      '# How-to guide',
      '',
      '## Prerequisites',
      '',
      '## Steps',
      '',
      '1. ',
      '',
      '## Verify',
      '',
    ].join('\n'),
    builtIn: true,
  },
  {
    id: 'builtin:api-reference',
    name: 'API reference',
    description: 'An endpoint reference with request and response examples.',
    suggestedPath: 'api/endpoint.md',
    contentRaw: [
      '---',
      'title: API endpoint',
      'tags: [api]',
      'status: draft',
      '---',
      '',
      '# API endpoint',
      '',
      '`GET /resource`',
      '',
      '## Request',
      '',
      '## Response',
      '',
      '```json',
      '{}',
      '```',
      '',
    ].join('\n'),
    builtIn: true,
  },
  {
    id: 'builtin:adr',
    name: 'Architecture decision',
    description: 'A concise record of context, decision, and consequences.',
    suggestedPath: 'decisions/0001-decision.md',
    contentRaw: [
      '---',
      'title: Architecture decision',
      'tags: [decision]',
      'status: draft',
      '---',
      '',
      '# Architecture decision',
      '',
      '## Context',
      '',
      '## Decision',
      '',
      '## Consequences',
      '',
    ].join('\n'),
    builtIn: true,
  },
];
